// <auto-generated />
using InterviewWebAPIQuestions.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InterviewWebAPIQuestions.Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241016094114_migration added")]
    partial class migrationadded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InterviewWebAPIQuestions.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Product A",
                            Price = 100m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Product B",
                            Price = 200m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Product C",
                            Price = 300m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Product D",
                            Price = 400m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Product E",
                            Price = 500m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
